import hat from './IMG.png'
import binance from './binance.png'
import meta from './meta.png'
import toko from './toko.png'
import trust from './trust.png'
import coin from './coin.png'
import avatar from './Background.png'
import placeholder from './placeholder.png'
import ParentPlaceholder from './Image.png'
export{hat, binance, meta,ParentPlaceholder, toko, trust, coin, avatar, placeholder}